### ISSUE TITLE
Parameter names for new glider variables

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#101]
How will vocabulary terms be reconciled for parameter names and units that are not found in the CF standard names or in udunits and will not pass the compliance checker?

**Comment by lukecampbell** [comment]
For CF and ACDD they will fail. The standard is pretty clear about that being a requirement. For the NCEI check it will maybe get a 1 out of 3 or something, not sure yet. For GliderDAC, we have a strict variable naming convention. That convention allows us to match the variable names to intended standard names and we could be more forgiving.

**Comment by robragsdale** [comment]
Their is an [IOOS parameter vocabulary](http://mmisw.org/orr/#http://mmisw.org/ont/ioos/parameter) on the MMI ORR that was created to supplement the CF standard names table terms.  Their is a [map](http://mmisw.org/orr/#http://mmisw.org/ont/ioos/map_ioos_cf) between the IOOS Parameter terms and the CF standard terms.  They try to follow CF conventions.  Would these pass the compliance checker test?

**Comment by lukecampbell** [comment]
Not ACDD or CF; as these standards are adopted by IOOS but not controlled or dictated by IOOS vocabulary. GliderDAC parameter names are strictly controlled so parameter names, and attributes must be uniform across datasets:

https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2

**Comment by kerfoot** [comment]
Migrating towards standardized vocabularies for instruments, platforms and institutions.  Examples:
1. platforms: https://vocab.nerc.ac.uk/search_nvs/B76/
2. instruments: http://vocab.nerc.ac.uk/collection/L22/current/
3. institutions/organizations: http://vocab.nerc.ac.uk/collection/B75/current/

Closing this issue and will open a generalized standardized vocabularies issue.
