### ISSUE TITLE
Update NGDAC-NetCDF-File-Format-Version 2

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#106]
Matt pointed out on our call today that our example text for attribution says "This work supported by funding from..."
https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2

This should be updated to show "Attribution: x,y,z" or something equivalent.

**Comment by kerfoot** [comment]
I think he might be confused (or I am): That's the NetCDF acknowledgement global attribute.  I thought we were using what was input on the attributions form field when the deployment is registered?  If this field was not filled out, then we were using this attribute to fill in the information.

I'd prefer not to impose restrictions on what users can and cannot use as values for NetCDF global attributes.

**Comment by BeckyBaltes** [comment]
You're right. It is the acknowledgement global attribute he's referring to.  I'll update him.

**Comment by lukecampbell** [comment]
The `acknowledgement` attribute is for free form attribution.

If you don't fill in the attribution form field here:
![attribution](https://cloud.githubusercontent.com/assets/1155163/16873755/43a18686-4a63-11e6-95aa-5f527ea77e88.png)

Then we use the `acknowledgement` attribute value in your first upload of your deployment.
Here:
![acknowledgement](https://cloud.githubusercontent.com/assets/1155163/16873797/736304d0-4a63-11e6-9ecf-029a7c12ba22.png)

All of this goes into the GliderDAC's internal database which stores very highlevel metadata about deployments. The entire database is available as  JSON API:

http://data.ioos.us/gliders/providers/api/deployment

The attribution attribute should be used by API clients to give proper attribution for the deployment.
