### ISSUE TITLE
Modeler systematic access to data by domain

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#107]
@kerfoot, @lukecampbell @kknee ,

See question I received from Fred Bahr today.  I feel like the answer should be yes, but I don't know how to do it.

*****
Becky,

Is there a way for Modelers to access the glider DAC programatically to find the current active gliders in their model domain.  Because glider names are not predictable (they incorporate both deployment date and glider serial number) it is hard to find the active glider unless you know the name from some other means.  One of our modelers would like to use a script find the current active gliders in the CeNCOOS/SCCOOS/NANOOS domains to assimilate into their model (the model is a west-coast ROMS, with a domain from Southern California to the Canadian border).

Fred

**Comment by lukecampbell** [comment]
Here's a notebook illustrating how

https://nbviewer.jupyter.org/gist/lukecampbell/8c47b3b110a1ed6f08d7cf658d71008e

GliderDAC doesn't have any geospatial search engine or anything like that but if you use a GIS library it should be possible to filter the deployments to a region of interest.
