### ISSUE TITLE
Glider Map data viewer missing?

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#108]
@kknee @lukecampbell , It looks like the data viewer is missing from the glider missions on the map.  If you click on a glider, it has the attribution but nothing else.  Does something need a reboot?

**Comment by kknee** [comment]
@lukecampbell seeing a few console errors:

![image](https://cloud.githubusercontent.com/assets/196868/18071688/da70733e-6e25-11e6-85b2-a5a1808cd7b9.png)

**Comment by lukecampbell** [comment]
Fixed

**Comment by lukecampbell** [comment]
Just a heads up, those console warnings are from the missing user login stuff. We should probably fix those, since the site doesn't have a login.

**Comment by kwilcox** [comment]
Was the SSL related?

**Comment by lukecampbell** [comment]
Yes

**Comment by lukecampbell** [comment]
no certificate errors or anything like that, just that python requests needed to accept redirects.
