### ISSUE TITLE
Documentation on the "type" attribute for instruments

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#109]
[Here](https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2#instrument_ctd) it gives the example attribute `instrument_ctd:type = "platform" ;`. Is this correct? I was expecting `instrument_ctd:type = "instrument" ;`.

**Comment by lukecampbell** [comment]
@kerfoot Could you weigh in here?

To the best of my knowledge there is no standard that describes an attribute `type` for an instrument variable. And I don't think it's used for anything by NODC for archiving. So, it can probably be a free-form attribute, but I'd like John to weigh in.

**Comment by kwilcox** [comment]
Glider DAC plugin for the CC requires it:

```
Corrective Actions

Name	Priority	Corrective action
Container Variables	2	instrument_ctd variable is missing required attribute type
```

**Comment by lukecampbell** [comment]
Correct, it requires it but it doesn't care what's inside the attribute, so you can set it to whatever you want.

**Comment by kerfoot** [comment]
Kyle,

I think you're right.  It should probably be set to instrument, not
platform.

John

**Comment by lukecampbell** [comment]
@kwilcox you can go ahead and set `instrument_ctd:type = "instrument";` good catch. We'll update the wiki with our next round of edits. 

I'd like to leave this issue open until the wiki is updated. The gliderDAC plugin doesn't check attribute contents, so we should be ok on that front.

**Comment by kerfoot** [comment]
Migrating towards standardized vocabularies for instrument, platforms, institutions, etc. Closing.
