### ISSUE TITLE
Three new deployments not showing up on ERDDAP/THREDDS

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#112]
I started uploading data last Friday and the deployments haven't appeared in ERDDAP or THREDDS as working datasets yet. Documentation says it should take 1-2 hours. Seems like there is an issue?

* `bass-20160909T1733` -  https://data.ioos.us/gliders/providers/users/secoora/deployment/57dbfc40c2fffe479dbe0f4e
* `modena-20160909T1758` - https://data.ioos.us/gliders/providers/users/secoora/deployment/57dc0127c2fffe479dbe0f4f
* `ramses-20160909T2028` - https://data.ioos.us/gliders/providers/users/secoora/deployment/57dc0169c2fffe2d11f6295f

Please note that `modena` and `ramses` are still in the water and uploading new data as it comes in. `bass` has a deployment issue and is no longer in the water (but I don't want it archived yet so it is not marked as `complete`).

**Comment by kerfoot** [comment]
@lukecampbell not sure what the issue is.  There are THREDDS .nc files, but they are completely empty and there's nothing on erddap?  Any ideas?

**Comment by lukecampbell** [comment]
I only checked modena.

There's no data in the files. They're not GliderDAC compliant.

- [Compliance Report](https://s3.amazonaws.com/asa-dev/transfer/modena.pdf)
- [modena_20160714T203635Z_rt.nc](https://s3.amazonaws.com/asa-dev/transfer/modena_20160714T203635Z_rt.nc)

**Comment by kwilcox** [comment]
This was a red herring, I should have uploaded anything before 201609. I just removed the offending files from the FTP.

The files there now score much better: https://data.ioos.us/compliance/report/f8d7b35e7833104477d8f0b4a233653fd45e98d8

**Comment by kwilcox** [comment]
ramses score: https://data.ioos.us/compliance/report/2d472099e94d9b50f9c9c58f0915d0152239a02f

**Comment by lukecampbell** [comment]
I'm gonna restart ERDDAP and manually kick off the processing job and see if I can see anything.

**Comment by lukecampbell** [comment]
Ok, so this is kind of a guess here, but I think that it's not working because `cdm_data_type` is defined in the file which contradicts what the datasets.xml file says.

The other deployments on GliderDAC don't define this attribute.

This is the error in the ERDDAP logs:
```
  accessibleViaNcCF=.ncCF/.ncCFMA isn't available for this dataset because cdm_data_type=Other is not a compatible type.                                                                   
```

I don't know where the `Other` comes from, neither the files nor the config specify other.

```
    <addAttributes>
        <att name="cdm_data_type">trajectoryProfile</att>
        <att name="featureType">trajectoryProfile</att>
        <att name="cdm_trajectory_variables">trajectory,wmo_id</att>
        <att name="cdm_profile_variables">time_uv,lat_uv,lon_uv,u,v,profile_id,time,latitude,longitude</att>
        <att name="subsetVariables">trajectory,wmo_id,time_uv,lat_uv,lon_uv,u,v,profile_id,time,latitude,longitude</att>
```

**Comment by lukecampbell** [comment]
Ok, bass and modena still have offending files. As for ramses, it looks good but seeing the error about cdm_data_type makes me think that the attribute is the reason it's not processing.

**Comment by kwilcox** [comment]
I think this came up recently in another issue somewhere...

From http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/metadata/DataDiscoveryAttConvention.html
```
cdm_data_type

The "cdm_data_type" attribute gives the THREDDS data type appropriate for this dataset. E.g., "Grid", "Image", "Station", "Trajectory", "Radial". Its use is recommended.
```

`trajectoryProfile` isn't a valid value for that attribute... does ERDDAP require it? I believe I'm doing the correct thing in the raw files.

**Comment by kwilcox** [comment]
> Ok, bass and modena still have offending files.

Meaning there are no compliance-checker-like tests run by the DAC to filter out bad real-time NetCDF files and I should implement something like this on my end?

**Comment by kerfoot** [comment]
@kwilcox the cdm_data_type global attribute is added in the datasets.xml file when the deployment is registered.  It helps ERDDAP take the entire series or profiles and aggregate them into a single trajectoryProfile data set.  Do the files you're submitting contain this attribute?  If so, remove it.  If not, we need to keep looking.  Can you email me a couple of the files you're writing?

**Comment by kwilcox** [comment]
Yes, they contain `:cdm_data_type = "Trajectory"` per ACDD standards.

**Comment by kwilcox** [comment]
I will remove the `cdm_data_type` global attribute when I re-upload all of the NetCDF files after filtering out "offending files" but the strife over this attribute will continue inside of my head!

**Comment by kwilcox** [comment]
OK I'm now filtering out bad profiles via the compliance checker and all four deployments are now showing up. Thanks for the help guys!

**Comment by lukecampbell** [comment]
so it was `cdm_data_type`  That's unfortunate. I'm glad we found the issue, but it's unfortunate that we didn't realize this could cause issues until. now. We'll be sure to add a blurb in the docs about it. 

Other global attributes _should_ work fine. We try to take the approach, "give us all you got, and we'll publish what we're capable of publishing".
