### ISSUE TITLE
Need fix for new glider deployment trajectory on glider map 

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#113]
New glider deployment roxy-20160914T2055 is showing up on the [glider Map](https://gliders.ioos.us/map/) in an improbable trajectory (it is basically a horizontal line cutting across Florida).

**Comment by lukecampbell** [comment]
https://data.ioos.us/gliders/erddap/tabledap/roxy-20160914T2055.htmlTable?latitude,longitude&time%3E=2016-09-09T00:00:00Z&time%3C=2016-09-16T12:34:14Z

Can someone reach out to Matt and ask him to check the coordinates on the submitted file?

**Comment by kerfoot** [comment]
@lukecampbell I will reach out to matt.  Any chance you can look at the submitted files and find the name of the bad one?

If so, could you delete this file?

**Comment by kerfoot** [comment]
@lukecampbell I think it's the first file: roxy-20160914T205510Z_rt.nc.  Can you ncdump -v lat roxy-20160914T205510Z_rt.nc and see if the bad lat is in there?

**Comment by lukecampbell** [comment]
```
lat = 21867.1824796184, 23117.9934558634, 24364.2980331578,
    25404.2178071372, 26443.8151048613, 27482.5938090146, 28727.7903909707,
    29768.288968485, 30804.5457429504, 31842.7043004591, 32885.7992252587,
    33924.8259880699
...
}
```

**Comment by lukecampbell** [comment]
The very next file:
```
lat = 27.2126395164437, 27.2126463914711, 27.2126531980105,
    27.2126599889992, 27.2126667557678, 27.2126735610067, 27.2126803368782,
    27.2126871047305, 27.2126939278501
```

**Comment by kerfoot** [comment]
@lukecampbell are you cool with deleting that bad file?  Is the file named: roxy-20160914T205510Z_rt.nc?  I will email Matt asking him to resubmit it.

**Comment by lukecampbell** [comment]
Yeah, I'll delete it tomorrow morning.
