### ISSUE TITLE
`valid_min` and `valid_max` not set to the correct type on some variables

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#117]
The `valid_min` and `valid_max` attributes should be of the same type as the data variable but this is not always the case with data coming from the DAC:

https://data.ioos.us/gliders//thredds/dodsC/deployments/mbari/UCSC260-20150520T0000/UCSC260-20150520T0000.nc3.nc.html

All of the `_qc` variables are offending. I didn't scan all of the datasets, it may occur on more.

**Comment by kwilcox** [comment]
Here is another: https://data.ioos.us/gliders//thredds/dodsC/deployments/lfiorentino/gichigami-20110630T2049/gichigami-20110630T2049.nc3.nc.html

The attributes are actually strings here... making it harder to figure out what it is suppose to be than the original example.

**Comment by lukecampbell** [comment]
Ok thanks. It's on our sprint this week to find all the datasets that have valid_min and valid_max issues and we'll reach out to the data providers to fix. 

Thanks for finding these. We'll expand our search to also look for type inconsistencies as well.

**Comment by lukecampbell** [comment]
We found the deployments that need to be corrected and we'll be working with the providers to correct these issues.

**Comment by benjwadams** [comment]
The issue for the datasets mentioned appears to have been fixed.  Closing.
