### ISSUE TITLE
remove "ancillary_varibles" from precise_lat and precise_lon in private erddap template

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#121]
@lukecampbell Can you remove the "ancillary_varibles" attribute from precise_lat and precise_lon?  Not only is it spelled wrong, but the user should be adding these, not us.

https://github.com/ioos/ioosngdac/blob/master/erddap/templates/private/dataset.deployment.xml#L199
and
https://github.com/ioos/ioosngdac/blob/master/erddap/templates/private/dataset.deployment.xml#L213

**Comment by lukecampbell** [comment]
could you make a PR for me? If not, I'll try to get to it next week or the week after.
