### ISSUE TITLE
Attribution not being displayed on map

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#122]
@lukecampbell For all 3 OOI glider deployments that I registered last week, the attribution is not being displayed when clicking on a glider track.  The message is "Attribution: No Attribution Provided".  I just checked the deployment registration page and all 3 of them say "National Science Foundation"

**Comment by lukecampbell** [comment]
Attribution comes from the `acknowledgement` global attribute.

**Comment by lukecampbell** [comment]
The UI element forces attribution to show up if `acknowledgment` is not defined. Just to note that it's the, in my opinion, incorrect spelling, or American, spelling of `acknowledgment` not the british spelling `acknowledgement` with the e in the middle.

**Comment by lukecampbell** [comment]
Actually, I got that backwards, it's acknowledgment if and only if the UI attribution isn't filled in.

**Comment by lukecampbell** [comment]
![screen shot 2017-04-03 at 11 05 44 am](https://cloud.githubusercontent.com/assets/1155163/24615863/80c28524-185d-11e7-9b92-235239a5b9c7.png)

**Comment by lukecampbell** [comment]
Attribution is filled in, so I don't know why it's not showing up on the map.

**Comment by lukecampbell** [comment]
Do you know where they're supposed to be on the map?

**Comment by kerfoot** [comment]
When I click on a glider track, a popup shows up displaying the name of the
deployment, graphing parameters, and "Attribution: No attribution provided".

**Comment by lukecampbell** [comment]
I think I found the issue, I'll let you know when I have something out.

**Comment by lukecampbell** [comment]
@kerfoot ok, now it should show up correctly on the map, could you let me know if it doesn't? You may have to force refresh if your browser cached the deployment metadata.

**Comment by kerfoot** [comment]
Looks good now. thanks!
