### ISSUE TITLE
variable_qc:flag_meanings and variable_qc:flag_values

### ISSUE THREAD

**Issue by bkirving** [ioos/ioosngdac#123]
There appears to be a duplicate qc flag. flag_values 6 and 7 both correspond to flag_meanings not_used. Do the meanings not_used apply to different processing steps? If so please clarify the difference. Otherwise, how should this be handled in the qc processing, just pick 6?

**Comment by kerfoot** [comment]
@bkirving Can you paste the link to the lines you're referring to?  I will check it out and reply.

**Comment by bkirving** [comment]
https://github.com/ioos/ioosngdac/blob/master/nc/template/IOOS_Glider_NetCDF_v3.0-qartod.cdl

https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2#lon_uv_qc

**Comment by kerfoot** [comment]
I think you're referring to the flags that end in "_qc".  If so, we have
moved to the qartod_*flag variables and are no longer using the *_qc
flags.  These flags will remain and will be used to store data provider qc
checks.

Please use the qartod_*flag variables if you are applying qartod qc.  If
not, leave the variable:ancillary_variables attributes empty and the DAC
will perform QARTOD checks and append the appropriate variables.

Does this make sense?  If not, let me know.

**Comment by bkirving** [comment]
It does make sense and I was following the discussion during yesterdays DAC webinar. 

However, can you still clarify whether the 2 not_used meanings are just a duplicate or I missed something in the documentation? Our processing has additional QA/QC steps and formatting requirements for agency data submission has been different in the past, i.e. not submitting individual files for each profile. Therefore, even though we're moving toward aligning with the DAC I'd like to keep a full qc record over the whole deployment/trajectory and it makes sense to use the old DAC flags.

**Comment by kerfoot** [comment]
I'm not sure what you mean by "are just a duplicate"?  Neither of those flag values are being used which is why they are have the "not_used" string.  You are free to define alternate meanings for any flag value that you would like to use.  We are just trying to provide guidance to all users when/if they use qc.

**Comment by bkirving** [comment]
That answers my question, thanks.
