### ISSUE TITLE
Identify impact of CF 1.7 on gliderdac datasets

### ISSUE THREAD

**Issue by Bobfrat** [ioos/ioosngdac#132]

**Comment by benjwadams** [comment]
This would be a good place to start:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#revhistory

**Comment by benjwadams** [comment]
Judging by the changelog, there seems to be a lot of projection and coordinate system related changes, which won't really have much of an effect on the metadata we're producing now.  A number of cell methods have been added in Appendix E. There are a number of errata, but most seem to be to clarify the conventions document.

Some things:

`actual_range`, `actual_min`, `actual_max` might be worth looking into.  My understanding is that `valid_*` represents the maximum permissible min/max of the data, *NOT* the min/max of the data present in the dataset.

Making sure standard names which imply positive/negative match with the `positive` attribute:  https://cf-trac.llnl.gov/trac/ticket/109
