### ISSUE TITLE
empty aoos deployment folders

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#135]
@kwilcox: I think you created the following 3 aoos deployments:

unit-167-20130911T0027
unit-191-20150711T2000
unit-4-20140910T1800

But there are no NetCDF files in  any of these folders.  Do you intend to submit NetCDF files for these deployments or should we delete the deployments?

**Comment by kwilcox** [comment]
I'll be submitting these soon

**Comment by kwilcox** [comment]
@kerfoot I submitted the first: https://data.ioos.us/gliders/providers/users/aoos/deployment/5a78bbf098723c2c0f74031a

If that ones processes OK through the DAC I've got the data ready for the next three to upload tomorrow.

**Comment by kerfoot** [comment]
@kwilcox I know we have discussed profile_ids before.  While it's not absolutely necessary, it would be easier on us (and end users) if you started your profile_ids at 1 and incremented them.  Any chance you can start at profile_id=1?

**Comment by kwilcox** [comment]
I do agree that the `profile_id` as a count is much more user friendly but we can't easily implement that. I'd like to keep the production of the netCDF files limited to the data available in the `*.*bd` data files. There are huge benefits here... a distributed system doesn't need to "know" about previous profiles, doesn't need to keep a tally of how many profiles have gone by, and doesn't need to list a directory of netCDF files just to figure out what its own `profile_id` should be. The only thing that goes into creating the netCDF files is the data files themselves (and some default metadata).

At any given time the DAC has a complete list of netCDF files in once place (the ftp directory). Would somewhere between the private ERDDAP and the public ERDDAP be a place to transition to a more user-friendly `profile_id` scheme on the DAC side?

**Comment by kerfoot** [comment]
All other data providers are able to keep a tally of the profile_ids (including myself) and increment them accordingly. So I'm not sure why it can't be easily implemented on your end.

With that said, go ahead an keep implementing it as you are...we will deal with it on our end.
