### ISSUE TITLE
deployment registration issue

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#136]
@benjwadams I was registering about 26 deployments this morning and, for about half of them, an nginx error page was displayed on submission.  However the deployments were still created.  Can you look in the logs and see if you can find the issue?

**Comment by kerfoot** [comment]
@benjwadams Here's a screenshot of what I'm seeing:

<img width="1680" alt="screen shot 2018-02-14 at 9 58 33 pm" src="https://user-images.githubusercontent.com/2778797/36238719-5c27d830-11d2-11e8-991b-4d055be72bff.png">

But the deployment is actually created.

**Comment by Bobfrat** [comment]
@benjwadams I assume this is related to https://github.com/ioos/ioosngdac/issues/139

**Comment by kerfoot** [comment]
This is still happening.  Any idea what the issue is?
