### ISSUE TITLE
operation not allowed for marking deployment as completed

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#139]
@benjwadams I just marked:

https://data.ioos.us/gliders/providers/users/rutgers/deployment/5a63532598723c2c0f740316

as completed and got the following response:
<img width="1680" alt="screen shot 2018-03-16 at 10 19 12 am" src="https://user-images.githubusercontent.com/2778797/37525573-a5d264b2-2903-11e8-90f8-1b560eab3669.png">

But the deployment was marked as completed

**Comment by benjwadams** [comment]
Odd, I'll check the nginx logs to see what's occurring.

**Comment by benjwadams** [comment]
Unable to reproduce this as a non-admin user when marking a deployment as complete.
