### ISSUE TITLE
NaN value in `time` variable

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#143]
The active deployment `sp034-20180514T1938` has a NaN value in the `time` variable: https://data.ioos.us/gliders/erddap/tabledap/sp034-20180514T1938.html. This has happened before but I finally caught a dataset in the act!

![screenshot 2018-05-22 at 2 40 15 pm](https://user-images.githubusercontent.com/13939/40383191-3ca4563a-5dce-11e8-9acb-ce9a2275ab5e.png)

**Comment by kwilcox** [comment]
Usually issues like this fix themselves over a few days

**Comment by benjwadams** [comment]
Uhh, this is strange:

```
ncdump -tv time /data/data/pub_erddap/drudnick/sp034-20180514T1938/sp034-20180514T1938.ncCF.nc3.nc | grep -A20 data:
data:

 time = "2018-05-14 20:04:15.000000", NaN, "2018-05-14 21:18:15.000000",
    "2018-05-14 21:55:15.000000", "2018-05-14 22:33:15.000000",
    "2018-05-14 23:42:0.000000", "2018-05-15 01:01:45.000000",
    "2018-05-15 02:20:15.000000", "2018-05-15 03:36:30.000000",
    "2018-05-15 04:53:30.000000", "2018-05-15 06:11:15",
    "2018-05-15 07:32:15.000000", "2018-05-15 08:50:30.000000",
    "2018-05-15 10:08:15.000000", "2018-05-15 11:26:15",
    "2018-05-15 12:44:15.000000", "2018-05-15 14:02:60.000000",
    "2018-05-15 15:21:60.000000", "2018-05-15 17:25:15.000000",
    "2018-05-15 19:41:45.000000", "2018-05-15 21:54:45.000000",
    "2018-05-15 23:27:15.000000", "2018-05-16 00:46:45.000000",
    "2018-05-16 02:07:30", "2018-05-16 03:25:30.000000",
    "2018-05-16 05:01:60.000000", "2018-05-16 06:47:15.000000",
    "2018-05-16 08:24:15.000000", "2018-05-16 10:08:45.000000",
    "2018-05-16 11:55:15.000000", "2018-05-16 13:42:0.000000",
    "2018-05-16 15:29:45.000000", "2018-05-16 17:59:45.000000",
    "2018-05-16 20:43:45.000000", "2018-05-16 23:17:60.000000",
    "2018-05-17 02:02:30.000000", "2018-05-17 04:50:45.000000",
    "2018-05-17 07:36:30.000000", "2018-05-17 10:23:0.000000",
```

I checked the files which comprise the original aggregation and I don't see a NaN.  If I try to request the same time range from the "private ERDDAP", I don't get this NaN.  I'm going to try to regenerate the file to see what it does.

**Comment by benjwadams** [comment]
As of right now, this looks like some sort of aggregation issue.  The data should also begin at 2018-05-14T19:38, as that's the first time entry in the first file of the aggregation.

**Comment by kerfoot** [comment]
Responsibility of the data provider to ensure no NaNs in the unlimited dimension (time). Closing
