### ISSUE TITLE
Update sample file generation script and docs

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioosngdac#144]
It looks like the sample python [program](https://github.com/ioos/ioosngdac/blob/master/util/createIoosGliderNcTemplate.py) (version 1.0), the [wiki](https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2) (version 2.0), and the [example cdl](https://github.com/ioos/ioosngdac/blob/master/nc/template/IOOS_Glider_NetCDF_v3.0-qartod.cdl) (version 3.0) are out of sync.  This came up at the recent IOOS DMAC annual meeting and I realized our documentation is confusing.

**Comment by kerfoot** [comment]
Obsolete. closing
