### ISSUE TITLE
Users can ftp files to their home directory

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#154]
Just found this out the hard way, but I was able to upload .nc files from a dataset to my data provider home directory.  I'm writing a python ftp script to push files and forgot to add the dataset folder name to the upload path.  But the files were transferred nonetheless.  Probably should not allow this.

**Comment by benjwadams** [comment]
I'm not entirely clear on the issue here, but I don't see any files uploaded to `/home` subdirectories, and users are chrooted in the current FTP setup.  I will need more clarification on what occurred here.

**Comment by kerfoot** [comment]
I wrote a python script to automate ftp transfers to the DAC.  In the
script, I forgot to set the dataset directory before I started uploading.
The files were successfully transferred to my data provider home
directory.  This was done on dev and I deleted the files, but can re-create
them if you need proof. Let me know

**Comment by benjwadams** [comment]
So the directory should be set to `/data/submission/$username`.  We can disable write bit on that particular directory, only relying on the providers application to create the subdirectories.  We'd likely have to have the application running as another user with write permissions so it can create the subdirectories.

**Comment by benjwadams** [comment]
As far as I know, this isn't easily addressable with Linux FACLs without also disabling write permissions in the "base" FTP virtual directory.   It's possible to disable write to the base directory, but then users will have to create a deployment only through the providers application.

**Comment by kerfoot** [comment]
Understood. I'll close this for now and we'll likely have to deal with the situation, when it comes up, by hand.
