### ISSUE TITLE
Remove some subset variables from datasets

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#156]
The following variables should be removed from the ERDDAP dataset subset service:

1. trajectory
2. wmo_id
3. time_uv
4. lat_uv
5. lon_uv
6. u
7. v

Current subset variables example:

[ru30-20220906T1523.subset]( https://gliders.ioos.us/erddap/tabledap/ru30-20220906T1523.subset)

There is only 1 trajectory and wmo_id for each data sets, so subsetting them based on these variables doesn't make sense. It also doesn't make sense to subset by depth-averaged currents, which is what the remaining variables do.

The list of variables providing subsetting should be:
1. profile_id
2. time
3. latitude
4. longitude

**Comment by benjwadams** [comment]
Created a PR.  Limited subset variables can also be tested on the dev ERDDAP server.

**Comment by kerfoot** [comment]
merged and closed.

**Comment by kerfoot** [comment]
Reopening...
@benjwadams Existing <dataset /> elements need to have the <subsetVariables /> attribute modified and the catalog needs to be reloaded to remove the bad subset variables.

**Comment by benjwadams** [comment]
This has to be applied to production -- will do shortly.

**Comment by kerfoot** [comment]
wmo_id and trajectory added to subset variables. Performance is exceptional. Closing.
