### ISSUE TITLE
Adding contributors for assigning tasks

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#158]
How do we add @DonaldMoretti and @leilabbb to this list of Assignees for this repo?

**Comment by mwengren** [comment]
I added @leilabbb to the gliderdac team.

@benjwadams You can add/remove members to the gliderdac team as necessary if the current list needs modification (however they first need to be members of the IOOS GH Org):  https://github.com/orgs/ioos/teams/gliderdac/members

**Comment by kerfoot** [comment]
Thanks. Can either @mwengren or @benjwadams add @DonaldMoretti also?

**Comment by kerfoot** [comment]
Also need to add @mdgrossi as well.

**Comment by kerfoot** [comment]
@mdgrossi added by @mwengren and I've been added as a maintainer of the [IOOS gliderdac team](https://github.com/orgs/ioos/teams/gliderdac) so that I can add existing IOOS contributors to the repo.

Adding new github users as contributors to the IOOS org, so that they can be added as repo contriubtors, must be done through @mwengren, @melissazweng or @MathewBiddle 

Closing
