### ISSUE TITLE
User submission directory not created on new account creation

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#166]
I created a provider user account for Jennifer Sevadjian at her request.  She was able to login to the [registration](https://gliders.ioos.us/providers/) page and change her password, but the data submission folder was not created.  She gets the following error when logging into the ftp server:

    500 OOPS: cannot change directory:/data/submission/jpsevadjian
    ftp: login failed

I think this means that she is unable to register deployments or, at a minimum, the submission location will not be created as the parent directory does not exist.

Need to:
1. Identify the cause of this and implement a fi
2. Create the /data/submission/jpsevadjian parent directory as user glider

**Comment by kerfoot** [comment]
I was able to sudo to user glider and manually create the top level user submission directory. Jenn confirmed that she is now able to connect to the ftp site.  We still need to figure out why the directory was not created when the account was registered.

**Comment by kerfoot** [comment]
2 new user accounts were created in the last week or so.  For both, the username directories were not created. This is the 3rd consecutive time this has happened, so it looks like this mechanism is broke.  The top level directory:

/data/data/priv_erddap/USERNAME

is no longer being created on account creation.

**Comment by benjwadams** [comment]
Fixed in latest deployed version.  Closing.
