### ISSUE TITLE
Deploy ERDDAP at glider DAC with all 2.0 files

### ISSUE THREAD

**Issue by dpsnowden** [ioos/ioosngdac#17]
@kerfoot and @lukecampbell, I'm starting this issue to track the progress and outstanding actions in deploying ERDDAP to the glider DAC servers.  We need a date by which this will happen soon.

@BobSimons,  FYI.  
@kknee I assigned this to you for your awareness, reassign to whoever makes sense.

We have currently...
1. The development [ERDDAP at rutgers](http://erddap.marine.rutgers.edu/erddap/info/index.html?page=1&itemsPerPage=1000)
2. The production [THREDDS](http://tds.gliders.ioos.us/thredds/catalog.html) which, I believe, contains only 1.0 files

The objective, according to the [architecture diagram](https://github.com/ioos/ioosngdac/wiki/NGDAC-Architecture), is to have a public ERDDAP and public THREDDS serving 2.0 files.  Another mandatory objective is to maintain the current 1.0 THREDDS implementation at least until we have a clear transition for NDBC that they approve, can implement, and have implemented.

**Comment by kerfoot** [comment]
closed
