### ISSUE TITLE
Provide DAC2.0 Server Details to NDBC

### ISSUE THREAD

**Issue by kknee** [ioos/ioosngdac#19]
Requested by Walt McCall for finalizing process for ingesting to GTS.

@lukecampbell @kerfoot are we ready to share these details?  If so, can one of you assign yourself to the issue and follow up with NDBC?

**Comment by kerfoot** [comment]
From Walt McCall at NDBC (via email) on 2014-02-19
While we are not fully implemented. We have finished enough testing to say that we are using the new system and will not use DAC 1.0 anymore. If we run into any issues, we will correct them rather than default to the old server. 

Walt
