### ISSUE TITLE
QC methods

### ISSUE THREAD

**Issue by thogar-computer** [ioos/ioosngdac#194]
Morning,

we are looking to implement some NRT QC on our glider data here at British Oceanographic Data Centre. Ideally, we would like to align with the wider community so have started looking at some of the pre-existing toolboxes. 

I noticed that your QC code is pulling from [ioos/qartod](https://github.com/ioos/qartod) which it seems is now deprecated and suggests new projects use [ioos/ioos_qc](https://github.com/ioos/ioos_qc). 

Within ioos_qc there is a glider QC file but it suggests using the [argo](https://github.com/ioos/ioos_qc/blob/main/ioos_qc/argo.py) code instead. 

I guess my question is, will you be moving to those Argo checks or are you planning to stay with the older glider ones?

Cheers
Tom

**Comment by kerfoot** [comment]
@benjwadams Are you saying that the [ioos_qc](https://github.com/ioos/ioos_qc) repo is EOL and will no longer be supported? If so, we need to rethink whether the DAC should move forward with using it in favor of "one of the newer libraries"? What "newer libraries" are you suggesting instead of [ioos_qc](https://github.com/ioos/ioos_qc)?

**Comment by ocefpaf** [comment]
BTW, ioos_qc is not deprecated as far as I know and we are interested in improving glider data QC with it.

**Comment by benjwadams** [comment]
> @benjwadams Are you saying that the [ioos_qc](https://github.com/ioos/ioos_qc) repo is EOL and will no longer be supported? If so, we need to rethink whether the DAC should move forward with using it in favor of "one of the newer libraries"? What "newer libraries" are you suggesting instead of [ioos_qc](https://github.com/ioos/ioos_qc)?

No, `qartod` (the older QC repo) is no longer maintained.  Closing issue as QC is slated for upgrade anyhow, and updated QC code will be a possible representative for QC code.

@thogar-computer, we should have something in place soon, I will post comment with your @ name posted once QC is updated to notify you.  For the time being, I'm going to close this issue out, as other issues likely cover similar ground.
