### ISSUE TITLE
Resolve DAC status page(s)

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#195]
I received another inquiry from a data provider asking me to explain why their data set was showing up as broken on:

https://gliders.ioos.us/status/

As discussed multiple times, this page is old, outdated and providing incorrect information on data set status.  It also requires time to respond to data provider inquiries that would otherwise be better spend elsewhere. The unfortunate thing about this is that this address intuitively makes more sense as the landing page for the current status page at:

https://gliders.ioos.us/status/datasets/

At some point we were made aware that there are other RPS apps that use some part of this page. The new status page includes an [API](https://gliders.ioos.us/status/datasets/api/) that likely provides the same (or better) information.  I would really like to do the following:

1. Get a list of RPS apps that use the old page
2. See if the existing [API ](https://gliders.ioos.us/status/datasets/api/)provides the same information
3. If no to the above, I can easily & quickly add other end points to provide the same responses that the old page did.

IMO this falls under infrastructure since it resolves old, undocumented dependencies that, when resolved, will harden the overall system and reduce confusion by data providers.

**Comment by benjwadams** [comment]
Most of the reason the old page is still used is for the static JSON endpoints which are used by a few other upstream processes.   In the near term, pages which aren't serving this sort of information can be used from your new status page application.

**Comment by kerfoot** [comment]
1. What, specifically, are the "upstream processes"?
2. What do you mean by "pages which aren't serving this sort of information can be used from your new status page application"?

**Comment by benjwadams** [comment]
Changed config to use John's glider status page, with single exception for static JSON page.

1) Aforementioned `status.json` file primarily appears to be used in the plot generation process here: https://github.com/ioos/glider-dac-status/blob/master/status/profile_plots.py
Although this is a more recent file than some of the other status page pieces, historically status has pulled from status.json.  It should really just pull from the database and the plot generation process ought to be moved to the main Glider DAC repo.

2. I'm not even sure what I meant there. However, for user facing portions of the status page 1) notwithstanding, we should replace the legacy page with your application.  That is, in fact, what I have done in effect.
