### ISSUE TITLE
Preventing users from transferring files to user home directory?

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#198]
The gcoos_dmac user has mistakenly uploaded profile NetCDF files to:

/data/data/priv_erddap/gcoos_dmac

instead of the corresponding data set location. For example, there are NetCDF files in:

/data/data/priv_erddap/gcoos_dmac

from sg624-20230711*.nc
to sg624-20230717*.nc

that should be in:

/data/data/priv_erddap/gcoos_dmac/sg624-20230712T1200

Is it possible to restrict file uploads only to a data set directory and not to the user's home directory?

Looks like this user has done this for many data sets.

**Comment by kerfoot** [comment]
I removed 2202 NetCDF files from /data/submission/gcoos_dmac.

**Comment by benjwadams** [comment]
I don't know of a way to do this -- `glider` user needs to be able to create directories in the "virtual home" directory FTP uses.  vsftpd also runs as this same user.
