### ISSUE TITLE
Handling of real-time vs delayed mode datasets

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#20]
We need to address the potential for a user to add delayed mode .nc files to the same directory as the real-time files.  This will create duplicate data, potentially causing problems for the aggregation.

Should we ask the data providers to create separate deployments for the realtime and delayed mode or delete real-time files once we see a delayed mode file hit the ftp server?

**Comment by kknee** [comment]
This issue needs to be revisited relative to NCEI archiving
