### ISSUE TITLE
Update catalog structure to prevent high frequency thredds restarts

### ISSUE THREAD

**Issue by lukecampbell** [ioos/ioosngdac#40]
> It'll need to be restarted more than that if we're creating and pointing to new catalog.xml files. If we use a single catalog.xml file with a datasetScan element that scans a single directory, we can restart only once per day as long as stability is not an issue.

**Comment by lukecampbell** [comment]
I was almost absolutely certain this was resolved but I can't find the changes in my branches, on my machine(s) and on production so it doesn't matter how certain I am, it's not there so I'm going to take a look at that.

What I did was added a deployments dataset scan that just looked in `/data/data/thredds` but I think somewhere during the git pulls that are automated the changes were blown away and I don't have a local copy because I'm a dufus.

**Comment by kerfoot** [comment]
@lukecampbell Still seems to be an issue as the most recent deployment:
http://54.91.88.156/deployment/54dce576d24895167773083f
was created yesterday, yet there is still no THREDDS end point after about 20 hrs.
