### ISSUE TITLE
Landing page for data.ioos.us/gliders

### ISSUE THREAD

**Issue by kknee** [ioos/ioosngdac#41]

**Comment by dpsnowden** [comment]
This is part of the overall consolidation of various pages focused on gliders.  The future of data.ioos.us/gliders and catalog.ioos.us/gliders are probably one and the same.

**Comment by Bobfrat** [comment]
@BeckyBaltes is this the [UG2 page](https://gliders.ioos.us/)? Or do you want a landing page in front of ERDDAP at http://data.ioos.us/gliders

**Comment by BeckyBaltes** [comment]
I think this is OBE. I think in 2015 the last time this was commented on, we didn't have a glider DAC page at all, so we can close this.
