### ISSUE TITLE
Deployments not making it to public ERDDAP

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#44]
The following deployments have not made it to the public erddap end point:

http://54.91.88.156/users/rutgers/deployment/54870de6d24895413f2ae38d
http://54.91.88.156/users/rutgers/deployment/5492e61cd248955ac2d6e2f4
http://54.91.88.156/users/rutgers/deployment/5492e75ad2489542cb8d3ecf

The NetCDF files have been uploaded, so the data sets should be there.

**Comment by lukecampbell** [comment]
Seeing these has led me down a hypothesis as to what is causing these hiccups. The first one has a lot of files that were all uploaded it looks like within one hour. I suspect that ERDDAP is trying to create the in-memory dataset or maybe an index of it, but it's unable to do so within the meager 30 seconds that the scripts expect.

**Comment by lukecampbell** [comment]
Well that wasn't it :\

**Comment by lukecampbell** [comment]
Ok, so these two new ones are all set.
