### ISSUE TITLE
Rutgers Gliders not showing up in ERDDAP or THREDDS

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#45]
@kerfoot @lukecampbell I checked for the 5 Rutgers gliders in the Arctic.  It does not appear that they made it into DAC v2,0, in either the [TDS](http://tds.gliders.ioos.us/thredds/catalog.html) or [ERDDAP](http://data.ioos.us/gliders/erddap/info/index.html?page=1&itemsPerPage=1000).  I checked the [WAF](http://data.ioos.us/gliders/metadata/) and it had not made it there either.   

[ru05-442](http://marine.rutgers.edu/cool/auvs/index.php?did=442&view=imagery)
[ru24-441](http://marine.rutgers.edu/cool/auvs/index.php?did=441&view=imagery)
[ru26d-439](http://marine.rutgers.edu/cool/auvs/index.php?did=439&view=imagery)
[ud_134-443](http://marine.rutgers.edu/cool/auvs/index.php?did=443&view=imagery)
[unit_191-440](http://marine.rutgers.edu/cool/auvs/index.php?did=440&view=imagery)

**Comment by dpsnowden** [comment]
Just FYI, you're mixing the version 1.0 TDS with the version 2.0 ERDDAP.
Not sure if you were aware but the version 2.0 TDS is at
data.ioos.us/gliders/thredds.

I realize this doesn't answer your question though.

On Tue, Jan 13, 2015 at 10:30 AM, robragsdale <notifications@github.com>
wrote:

> @kerfoot <https://github.com/kerfoot> @lukecampbell
> <https://github.com/lukecampbell> I checked for the 5 Rutgers gliders in
> the Arctic. It does not appear that they made it into DAC v2,0, in either
> the TDS <http://tds.gliders.ioos.us/thredds/catalog.html> or ERDDAP
> <http://data.ioos.us/gliders/erddap/info/index.html?page=1&itemsPerPage=1000>.
> I checked the WAF <http://data.ioos.us/gliders/metadata/> and it had not
> made it there either.
>
> ru05-442
> <http://marine.rutgers.edu/cool/auvs/index.php?did=442&view=imagery>
> ru24-441
> <http://marine.rutgers.edu/cool/auvs/index.php?did=441&view=imagery>
> ru26d-439
> <http://marine.rutgers.edu/cool/auvs/index.php?did=439&view=imagery>
> ud_134-443
> <http://marine.rutgers.edu/cool/auvs/index.php?did=443&view=imagery>
> unit_191-440
> <http://marine.rutgers.edu/cool/auvs/index.php?did=440&view=imagery>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/ioosngdac/issues/45>.
>



-- 
Derrick Snowden
Chief, Operations and Communications Division
NOAA/NOS/US Integrated Ocean Observing System Program
<http://www.ioos.noaa.gov>
1100 Wayne Ave, Suite 1225
Silver Spring, MD 20912
+1 301 427 2464 (o), +1 301 427 2073 (f)
Facebook <http://www.facebook.com/usioosgov> | Twitter
<https://twitter.com/usioosgov>

**Comment by lukecampbell** [comment]
@kerfoot could you verify that they were uploaded?

**Comment by kerfoot** [comment]
I ran into some issues posting the data sets.  Am in the process of trying
to resolve.

John

**Comment by kerfoot** [comment]
They have NOT been uploaded yet.

**Comment by robragsdale** [comment]
Thanks for the update @kerfoot.  I copied the wrong TDS url.  I am aware of TDS 2.0 and the url.
