### ISSUE TITLE
Catalog dataset mislabeled

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#47]
Kelli Page (GLOS Director) checked out the catalog and noticed that the lone GLOS dataset has John Kerfoot as the platform sponser. Can you update it?  @lukecampbell @kerfoot  I assume this is the Russ Miller set.

http://catalog.ioos.us/datasets/542365c446a46b7a7321520a

**Comment by kerfoot** [comment]
Not sure where that metadata is coming from as the NetCDF files contain the proper attribution:

http://data.ioos.us/gliders/erddap/tabledap/unit_236-20121005T2349.html

maybe this catalog entry was from an old dataset?

**Comment by robragsdale** [comment]
@kerfoot You are identified in the [file](http://www.ngdc.noaa.gov/metadata/published/NOAA/IOOS/Glider_DAC/iso_u/xml/unit_236-20121005T2349.nc3.nc.thredds.xml) registered in the DAC WAF as the Responsible Party.  I don't know whether this is being translated to Platform sponsor.  This is from the xml.   
<gmd:citedResponsibleParty>
<gmd:CI_ResponsibleParty>
<gmd:individualName>
<gco:CharacterString>John Kerfoot</gco:CharacterString>

By updating the file, will that fix the discrepancy?

**Comment by kerfoot** [comment]
I'm not sure where that file/entry came from.  The metadata taken directly from the files uploaded to the DAC has the proper attribution (ie: GLOS, summary, etc):

http://data.ioos.us/gliders/erddap/tabledap/unit_236-20121005T2349.html

**Comment by BeckyBaltes** [comment]
The link you have attached has your name in it though.  Where is it listed correctly?

**Comment by kerfoot** [comment]
It has my name in it because I did the data processing and wrote the
files.  But institution and summary as well as other contributors are all
correctly identified as GLOS.

**Comment by BeckyBaltes** [comment]
I notified Kelli.
