### ISSUE TITLE
OSMC Interface

### ISSUE THREAD

**Issue by lukecampbell** [ioos/ioosngdac#50]
http://osmc.noaa.gov/erddap/tabledap/OSMCV4_DUO_PROFILES.htmlTable?platform_code,platform_type&platform_type=%22GLIDERS%22&time%3E=2015-03-17T00:00:00Z&distinct()&orderBy(%22platform_code,platform_type%22)

**Comment by Bobfrat** [comment]
Working on querying the osmc endpoint for last 24 hrs of released profiles organized by wmo_id

**Comment by benjwadams** [comment]
Link appears to time out and initial issue is not clear from the context.  Closing.
