### ISSUE TITLE
Allow custom bounding box search

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/ioosngdac#55]
In addition to choosing by provider region from a dropdown, would it be possible to select by rubberbanding a region to find glider data in?    I might want to find glider data in long island sound, but perhaps I'm not sure what region that is in.   (actually, I think it's in both NERACOOS and MARACOOS).

Is it okay to raise issues like this here?

![5-26-2015 12-42-32 pm](https://cloud.githubusercontent.com/assets/1872600/7817711/cfa4c96a-03a4-11e5-899b-5d486a4a44f0.png)

**Comment by kerfoot** [comment]
Hi Rich,

I think it's fine to use this email for requests.  We're looking for as much feedback and suggestions that we can get.  We have typically used github issues for this in the past.  I can add you as a collaborator if you'd like?

Let's discuss this more over the next couple of days at the DMAC meeting.  I am looking to getting some feedback and suggestions now that the DAC is relatively stable.

See you tomorrow.

John

**Comment by Bobfrat** [comment]
This is an issue that will be addressed IOOS program wide (IOOS EDS viewer) that should eventually get into the gliderdac viewer.

@mwengren
