### ISSUE TITLE
Harmonize global attributes between IOOS and EGO

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/ioosngdac#56]
The European Glider Organization Users Manual v1.1 is here:
http://dx.doi.org/10.13155/34980

It would be nice to harmonize the global attribute information between EGO and IOOS in some future version of EGO or IOOS.

**Comment by kerfoot** [comment]
@rsignell-usgs : at first glance, I think we're pretty close (i.e.; wmo_platform_code vs wmo_id, area vs sea_name).  Shouldn't be a problem to reconcile moving forward.  But I'm wondering: how to handle datasets that have already been submitted?

**Comment by rsignell-usgs** [comment]
Yes, pretty close!   Maybe we could just convince EGO to change in their next version.  :grinning:

**Comment by Bobfrat** [comment]
Still on our radar

**Comment by kerfoot** [comment]
Closing as obsolete.  The plan is to harmonize with the [IOOS Metadata Profile](https://ioos.github.io/ioos-metadata/) and the [OG1.0 specification](https://github.com/OceanGlidersCommunity/OG-format-user-manual)
