### ISSUE TITLE
Profile file name timestamps in UTC?

### ISSUE THREAD

**Issue by shane-axiom** [ioos/ioosngdac#57]
This is pretty trivial, but I try to point it out whenever I see it. The timestamps in the profile file names don't have a Z to indicate that they're in UTC. I'm assuming they're in UTC and not local time, but it would be nice to include the Z to make it unambiguous.

If this is documented somewhere or unimportant, I won't be offended if this issue is declined. Just wanted to mention it...

**Comment by kerfoot** [comment]
Hadn't thought about this since I always use and assume UTC.  I updated the wiki with this convention.  Thanks.
