### ISSUE TITLE
Run GliderDAC checker on existing files

### ISSUE THREAD

**Issue by kknee** [ioos/ioosngdac#67]
or manually inspect, as appropriate

**Comment by lukecampbell** [comment]
I ran it on the existing files, but we want to check the data provider provided profiles now.

**Comment by Bobfrat** [comment]
Potentially build this into the upload tool front end. Provide users with a link to the report and score.

**Comment by kerfoot** [comment]
Done. Compliance checker is run on new data sets.  Need to check on when this done. closing.
