### ISSUE TITLE
Can't add WMO id after creating a deployment

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#68]
I'm trying to add the WMO id for the following deployment:

http://data.ioos.us/gliders/providers/users/rutgers/deployment/555616f5dd5fa9082ee3f17a

but there's not input box.

**Comment by kerfoot** [comment]
Also, I'm unable to mark deployments as complete.  The checkbox is disabled.

**Comment by lukecampbell** [comment]
Can you verify that you're logged in as an administrator?
![screen shot 2015-07-14 at 2 50 04 pm](https://cloud.githubusercontent.com/assets/1155163/8681809/ac36c24e-2a37-11e5-86df-849c849628c0.png)

**Comment by Bobfrat** [comment]
No longer relevant
