### ISSUE TITLE
Invalid Glider DAC link in navbar

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#69]
The link to the glider DAC ("Glider DAC v2") points to:

http://data.ioos.us/providers/

it should point to:

http://data.ioos.us/gliders/providers/

**Comment by kknee** [comment]
The broken link is in the nav bar here: http://data.ioos.us/gliders/providers

**Comment by lukecampbell** [comment]
![screen shot 2015-07-07 at 2 13 51 pm](https://cloud.githubusercontent.com/assets/1155163/8553580/6d8e3d22-24b2-11e5-862c-0947517e7727.png)

**Comment by lukecampbell** [comment]
Sorry, I thought this was the proxy thing.
