### ISSUE TITLE
standard-name sea_water_salinity vs sea_water_practical_salinity

### ISSUE THREAD

**Issue by RussellSenior** [ioos/ioosngdac#70]
I was just reading http://cfconventions.org/Data/cf-standard-names/27/build/cf-standard-name-table.html for sea_water_salinity and the guidance there suggests that the preferred standard name for modern measurements is sea_water_practical_salinity, which in turn says:  "[sea_water_practical_salinity] should be used to describe salinity observations made from 1978 onwards (Practical Salinity is the salinity quantity stored by national data centres for post-1978 observations). The only exception to this is where the observed salinities are definitely known not to be recorded on the Practical Salinity Scale."

**Comment by kerfoot** [comment]
@RussellSenior Change made and new .nc, .cdl and .ncml templates commited:

https://github.com/ioos/ioosngdac/commit/fbd5e0e98b08dbf303268c1e78e394079e0a4666
