### ISSUE TITLE
Running checker on AOML data to submit

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#76]
Francis Bringas corrected issues with their nc files so they should now be compatible with the glider DAC format requirements. 

Could @lukecampbell please check that this new file is compliant? (See attachment in email sent on 8/10) The corresponding 'OLD' file is also in attachment to compare.  

Francis will try to install the IOOS compliance checker but it may take some time until I have that program running locally. 

Just for curiosity: are there any plans to have that checker running online so that users can load a file online and run the check instead of installing the code?

**Comment by lukecampbell** [comment]
I think this was done.

**Comment by robragsdale** [comment]
@lukecampbell It looks like Francis Bringas' (AOML) gliders are processing through the GliderDAC workflow from the [catalog status monitor](http://catalog.ioos.us/services/filter/) and [ngdac 2.0 status page](http://data.ioos.us/gliders/status/) pages.   If the corrections he made to the nc files are not working, could you please let me know so I can follow up with him about the issue? Thanks.

**Comment by lukecampbell** [comment]
Yeah, confirmed they're all good.
