### ISSUE TITLE
deployment registration date input placeholder value

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#77]
Change the placeholder value for 'Deployment Date' to the recommended format string: YYYY-MM-DD HH:mm

**Comment by kwilcox** [comment]
Ijgurgh Jun

**Comment by kwilcox** [comment]
My phone went crazy... sorry about that...

**Comment by lukecampbell** [comment]
Where does this go? And what's going on with all the reassignments?

**Comment by kerfoot** [comment]
@lukecampbell: It should go in the 'placeholder' attribute on  the #deployment_date input element.

**Comment by lukecampbell** [comment]
Oh, got it you actually mean HTML placeholder. I thought we were talking about netCDF attributes.

**Comment by kerfoot** [comment]
Yep, the placeholder attribute on the input element.  It will provide a little guidance to providers.  thanks.

**Comment by lukecampbell** [comment]
![screen shot 2015-11-03 at 11 26 31 am](https://cloud.githubusercontent.com/assets/1155163/10913857/c1b87db8-821d-11e5-9d62-6edfce18c824.png)
