### ISSUE TITLE
`completed` flag not carried over to ERDDAP

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#78]
I'm trying to determine which glider deployments are `completed`.  I can see the `completed` flag is part of the internal Glider DAC data model (https://github.com/ioos/glider-dac/blob/master/glider_dac/models/deployment.py#L28) but can not find this information in the data provided through ERDDAP.

**Comment by kerfoot** [comment]
It's not anywhere in the ERDDAP datasets.  It's primarily used for NCEI archiving purposes.  When the user marks the deployment as complete, an MD5 sum is generated for the datasets.  NCEI has a ssh login that allows them to log in and find all datasets that have an MD5.  If they find the 2 files, they archive the deployment.

**Comment by kwilcox** [comment]
I'd also like to do some post-processing on deployments that are `completed`.  Is it possible to add it as a new global attribute in the publicly accessible dataset(s)?

**Comment by dpsnowden** [comment]
So this was closed but what was the resolution?

**Comment by robragsdale** [comment]
To resolve this, Luke made changes to the GliderDAC metadata model so that now their is a completed deployment attribute to identify "complete" deployments.

**Comment by lukecampbell** [comment]
It's actually been there since I developed the API last year. 

http://data.ioos.us/gliders/providers/api/deployment
