### ISSUE TITLE
Garbled characters in some global attributes (encoding issue)?

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#79]
Some datasets coming from ERDDAP and THREDDS contains garbled characters in the global attributes. All of the cases I have found are from the word `Ad��lie`

Example `ru05-20150105T1600`, the global attribute `summary`.

http://data.ioos.us/gliders//thredds/dodsC/deployments/rutgers/ru05-20150105T1600/ru05-20150105T1600.nc3.nc.html
http://data.ioos.us/gliders/erddap/tabledap/ru05-20150105T1600.html

**Comment by kerfoot** [comment]
This is my dataset and I'm guessing I copied and pasted the summary from a word doc to the CDL.  Will check on this and update.

**Comment by lukecampbell** [comment]
The data provider has been notified.
