### ISSUE TITLE
Inconsistent use of `id` global attribute

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#81]
The `id` global attribute should not include the "Z" after the timestamp, but the following deployments do:

```
bass-20150706T151619Z
Murphy-20150809T1355Z
Stommel-20150805T0000Z
unit_308-20150701T222927Z
unit_540-20150701T181602Z
```

**Comment by kknee** [comment]
This is an artifact of a temporary naming convention change.  @kerfoot and @lukecampbell will work to update these files.

**Comment by lukecampbell** [comment]
@kerfoot If we update or rename these deployments, I'm afraid it will break a lot of automation. All of the data providers are mkhoward.  Can we just let these be? There is a potential for backlash if we change them at this point:

- Break automation for provider
- Causes dangling metadata records in catalog
- Any 3rd party that may have statically linked to these particular deployments would break. 

Each of these have been collecting data over a month.

**Comment by Bobfrat** [comment]
@kwilcox Is there a negative consequence to this we're not aware of? Can we close? Going forward we will try to ensure there is no Z appended to the id's.

**Comment by kwilcox** [comment]
Just triggers my ocd. Probably not reason enough to cause the headaches @lukecampbell described.
