### ISSUE TITLE
Some datasets have the default "filler" summary global attribute

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#82]
`This is a summary of the Originator, Group, Mission whatever` is in:

```
bass-20150706T151619Z
unit_308-20150701T222927Z
unit_540-20150701T181602Z
```

**Comment by kerfoot** [comment]
@kwilcox : yes, these are all from the same data provider and I've tried to stress the importance of a well-worded summary.  We've had numerous discussions about this and decided that we can't enforce the content of the attributes, just that they are there.
