### ISSUE TITLE
Some deployments have NaNf values instead of using the FillValue

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#84]
**Example:** The first bunch of records of `temperature` in the `SG609-20150206T1720` deployment.

```
temperature = NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, 
    NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, NaNf, 
    NaNf, NaNf, NaNf, 6.039431, 6.160538, 6.153492, 5.984578, 5.844659, 
    5.85451, 5.981521, 5.980494, 6.11886, 6.113203, 6.126954, 6.140103,
...
```

**Comment by lukecampbell** [comment]
I can't speak on behalf of the provider but they may not be fill values.

**Comment by kerfoot** [comment]
This is a data provider issue in the sense that they explicitly put these values in the data array and they may (or may not) by intentional.  We will contact the data provider and make them aware of the situation.

**Comment by fbringas** [comment]
The NaNf values were not intentional. This issue has been fixed and the data files updated in the IOOS Glider DAC.
