### ISSUE TITLE
Draft Summary para for NCEI archive 

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#85]
Could you write a short paragraph about what the NGDAC did with the data once it was received.  This could then be appended as a second paragraph to whatever summary was provided by the submitter.  This would ensure that at least some pertinent information was included in the abstract section of a Archival Information Package (AIP) that NCEI disseminates.

**Comment by robragsdale** [comment]
All, here is a short paragraph to augment the data provider summaries: 

Glider deployment files submitted to the IOOS NGDAC are validated by the IOOS compliance checker, aggregated into a single dataset that represents the deployment or trajectory, and distributed via ERDDAP and THREDDS endpoints.  The glider file data provider marks the deployment complete and an md5 checksum is generated for the trajectory NetCDF file.  When the deployment is completed, the data set is added to the National Centers for Environmental Information (NCEI) archive.   

I will distribute this if everyone is ok with it. Please make edits if you have them.  Thanks.

**Comment by kerfoot** [comment]
Hi Rob,

Thanks.

I think we want to say a little more about the data itself.  I will review
tonight and send out an updated version tomorrow morning.

John

**Comment by kerfoot** [comment]
How about something like:

The Integrated Ocean Observing System's National Glider Data Assembly
Center receives sets of individual NetCDF files comprising an individual
glider deployment from data operators and providers around the world.
These files are checked for compliance and then aggregated into a single
data set representing the entire deployment and made available via ERRDAP
and THREDDS end points, making the data sets available to the public.
Currently, the data sets provide measurements of physical oceanographic
properties (temperature, salinity, conductivity and density).  Future
plans, currently under development, include providing access to biological
and chemical properties.  Once the deployment has been completed, as
specified by the glider operator or data provider, the data set is marked
for archiving, at which point it is added to the National Centers for
Environmental Information (NCEI, formerly NODC) data archive to create a
permanent archive of the data set.

John

**Comment by robragsdale** [comment]
John, I like your revisions.  Does anyone have comments?  If not, then I will close this later today and distribute to the glider data providers.

**Comment by robragsdale** [comment]
@kerfoot @lukecampbell 

Corrected a typo "ERRDAP" should be "ERDDAP".  This version has the fixed typo:

The Integrated Ocean Observing System's National Glider Data Assembly Center receives sets of individual NetCDF files comprising an individual glider deployment from data operators and providers around the world. These files are checked for compliance and then aggregated into a single data set representing the entire deployment and made available via ERDDAP and THREDDS end points, making the data sets available to the public. Currently, the data sets provide measurements of physical oceanographic properties (temperature, salinity, conductivity and density). Future plans, currently under development, include providing access to biological and chemical properties. Once the deployment has been completed, as specified by the glider operator or data provider, the data set is marked for archiving, at which point it is added to the National Centers for Environmental Information (NCEI, formerly NODC) data archive to create a permanent archive of the data set.

**Comment by kknee** [comment]
With the typo correction I think we are all set.
