### ISSUE TITLE
What type of CTD Data should be submitted?

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#89]
Chad Lembke wants to confirm this because in order to answer to answer his colleague's questions.  

Does the DAC take unpumped Slocum CTD data? 
Uncorrected CTD data included calculated salinity and density should be submitted? Correct?

Could not find information on types of data to submit on the Wiki.  Did I miss it?  If it is there could you point me to it and I will get back to Chad.  If not, it might be good to add this type of information.

**Comment by lukecampbell** [comment]
@kerfoot could you comment on this?

**Comment by kerfoot** [comment]
1. Both pumped and unpumped CTD data are accepted by the DAC.  Ideally, we'd like the user to specify, using the instrument:ctd attribute, which type was submitted.  See the doco:

https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2#instrument_ctd

In this example, here's the comment attribute:

instrument_ctd:comment = "pumped CTD" ;

As far as QA/QC of CTD data (salinity, density) with respect to time and thermal lags, is ultimately up to the data provider.  The data provider should make use of the corresponding VARIABLE_qc variable to specify the degree of QA/QC applied, if any.

I will add a blurb on the wiki stating explicitly that both pumped and unpumped data are accepted.
