### ISSUE TITLE
Gichigami-20110629T1821 actualy contains many deployments

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#91]
The `Gichigami-20110629T1821` ERDDAP/THREDDS dataset actually contains 10 deployments with the same `wmo_id`

* gichigami-20110629T1821
* gichigami-20110630T2049
* gichigami-20110701T0123
* gichigami-20110701T1556
* gichigami-20110702T1048
* gichigami-20110703T0859
* gichigami-20110704T0352
* gichigami-20110705T1936
* gichigami-20110706T1754
* gichigami-20110707T0056

I couldn't find another dataset using this format. Should these be split up into different deployments by the glider DAC, or is this format going to be common going forward? I thought the base unit for a Glider DAC dataset in THREDDS and ERDDAP was a single Deployment?

**Comment by kerfoot** [comment]
She must have put them all in the same directory and we have erddap set up to aggregate by time AND trajectory.

I'll ask her to delete the files and make sure to upload to the proper directories.

John

**Comment by kknee** [comment]
@kwilcox unfortunately this data provider has since left the UMD lab.  We'll attempt to fix these deployments manually.

**Comment by kknee** [comment]
@lukecampbell this is all set, yes?

**Comment by lukecampbell** [comment]
Yes
