### ISSUE TITLE
Inconsistent platform `id` metadata

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#94]
The following deployments have two different values for the platform `id`, one from the `id` global attribute and the other from the `id` attribute on the `platform_meta` variable:
- Stommel-20150805T0000Z - `Stommell` vs `540`
- Sverdrup-20150822T1639 - `Sverdrup` vs `540`
- unit_308-20150701T222927Z - `unit_308` vs `540`

**Comment by lukecampbell** [comment]
I don't believe we have any requirements directing the usage of either of these attributes.
We'll be sure to let the provider know.
https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2

**Comment by kerfoot** [comment]
Data provider responsibility, but it is our responsibility to let them know this is an issue and create include in a best practices wiki section.  Will also put together a few "gold standard" NetCDF files for users to use as templates. Closing.
