### ISSUE TITLE
Some profiles start before the previous profile ends

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#95]
I've noticed that in a very small number of Deployments there are profiles that start before the previous profile has ended.  This is based on the `precise_time(obs)` variable and not the `time(profile)` variable. I haven't identified all of the offending Deployments, but here are a few:
- bass-20150706T151619Z
- Murphy-20150809T1355Z
- Stommel-20150805T0000Z
- unit_308-20150701T222927Z
- unit_540-20150701T181602Z

[Here is a notebook](https://gist.github.com/kwilcox/9cca7e907815c9b5ee1e) showing the problem. The file I'm accessing was [downloaded from ERDDAP](http://data.ioos.us/gliders/erddap/tabledap/bass-20150706T151619Z.ncCF?trajectory,wmo_id,time,latitude,latitude_qc,longitude,longitude_qc,time_qc,depth,depth_qc,pressure,pressure_qc,conductivity,conductivity_qc,density,density_qc,precise_lat,precise_lon,precise_time,profile_id,precise_lat_qc,precise_lon_qc,precise_time_qc,salinity,salinity_qc,temperature,temperature_qc,time_uv,time_uv_qc,lat_uv,lat_uv_qc,lon_uv,lon_uv_qc,u,u_qc,v,v_qc,platform_meta,instrument_ctd) as a `.ncCF - Download a NetCDF-3 CF Discrete Sampling Geometries file (Contiguous Ragged Array).`

**Comment by lukecampbell** [comment]
This is up to the providers. GliderDAC does not have or maintain policies directing continuity for deployments, or overlapping times. We can let them know that it's causing problems for you but as far as I know, we don't have any intention to direct them otherwise.
