### ISSUE TITLE
New Data Provider at UW needs WMO ID

### ISSUE THREAD

**Issue by robragsdale** [ioos/ioosngdac#96]
@kerfoot Can you please follow up with Beth Curry at UW - APL who needs a WMO ID for a new glider deployment.  She is a new data provider and here is her information: 

Contact Name: Beth Curry
Contact Organization: Applied Physics Laboratory, University of Washington
Email Address: beth4cu@uw.edu
Telephone Number: 206-685-8326

and glider deployment that she needs a WMO ID for: 

Data provider: Applied Physics Laboratory, University of Washington
Glider name: SG187
Deployment date: June 2015
Deployment location: 47.7623N, -125.0883W

Thank you!

**Comment by lukecampbell** [comment]
Just a follow up from the email thread, her deployment has a WMO ID as it is already going to the GTS directly from the collector. We're still trying to sort out how we should integrate this into GliderDAC but avoid duplicate submissions to the GTS.
