### ISSUE TITLE
Upgrade ERDDAP to 1.68 

### ISSUE THREAD

**Issue by kerfoot** [ioos/ioosngdac#98]
I upgraded my local erddap server to 1.68, which has the axis reverse option available:

http://erddap.marine.rutgers.edu/erddap/tabledap/ru29-20150623T1046.largePng?time,depth,temperature&orderBy(%22time%22)&.draw=markers&.marker=6|10&.color=0xFFFFFF&.colorBar=Rainbow2|||4|25|&.bgColor=0xffccccff&.yRange=||false

Pretty nice and I think end-users will love it.  Can we upgrade when you've got time?

**Comment by kwilcox** [comment]
Plugging https://github.com/axiom-data-science/docker-erddap/blob/master/README.md

**Comment by kerfoot** [comment]
@lukecampbell Can we upgrade ERDDAP to the latest and greatest (v1.72)?  I'm running it locally and the y-axis inversion option is pretty nice:

http://erddap.marine.rutgers.edu/erddap/tabledap/silbo-20160413T1534.graph?salinity%2Cdepth%2Cprofile_id%2Ctime&time%3E=2016-07-10T03%3A27%3A20Z&orderBy(%22time%22)&.draw=markers&.marker=3%7C5&.color=0xFFFFFF&.colorBar=%7C%7C%7C%7C%7C&.yRange=%7C%7Cfalse&.bgColor=0xffccccff

**Comment by lukecampbell** [comment]
When I upgraded last time it broke GliderDAC, I don't currently have the resources to test and find out why it wasn't working. This is still on my to-do list, though.

**Comment by kerfoot** [comment]
Any chance we can bump this up the priority list?  I've had a number of people ask if it's possible to reverse the y-axis when plotting profiles and cross-sections.

**Comment by lukecampbell** [comment]
Just to put why we didn't update last cycle. The java version running on that box is like 1.6, we'd need to update to 1.8 which is non-trivial and would likely break a lot of stuff. I would need to schedule a large block of downtime, make a clone of the DAC which would take a day, and test the upgrade on the clone to see what breaks.

**Comment by kerfoot** [comment]
So does that mean it's unlikely it will happen anytime soon?  The version we're running is very old.

**Comment by rsignell-usgs** [comment]
@lukecampbell and @kerfoot , how about using the Docker container for ERDDAP?
https://hub.docker.com/r/axiom/docker-erddap/

We've been using this at USGS and on the OOI-CGSN OMS++ project and it works great.

If you use the 1.74 version
`docker pull axiom/docker-erddap:1.74` 
you get an extra bonus:  the netcdf-java jar file has been updated so that it can read the latest netcdf4 files produced by folks using the C library (e.g. netcdf4-python).

**Comment by lukecampbell** [comment]
This linux version is too old to run docker as well. :\

**Comment by kwilcox** [comment]
@kerfoot @rsignell-usgs I put all of the glider data on another ERDDAP instance. Feel free to use it or point people at it while the DAC finds time to upgrade their server: http://ioos.erddap.axiomdatascience.com/erddap/info/index.html

**Comment by kerfoot** [comment]
ERDDAP updated to v1.78.  Everything functioning normally. closing.
