### ISSUE TITLE
ERDDAP restart schedule

### ISSUE THREAD

**Issue by kwilcox** [ioos/ioosngdac#99]
What is the schedule that the Glider DAC restarts the public facing ERDDAP?

**Comment by lukecampbell** [comment]
It's only restarted as needed, the last time it was restarted was on 24 Feb

**Comment by kwilcox** [comment]
Thanks!

**Comment by lukecampbell** [comment]
Were you hoping it would be restarted more frequently?

**Comment by kwilcox** [comment]
I'm having periodic connection issues and has been assuming for weeks I was trying on the same schedule that it was restarting.  I'll have to poke around some more and figure this out.

**Comment by lukecampbell** [comment]
Yeah it looks like we have a few people trying to download all of gliderdac every day at midnight. Here's the CPU:

![screen shot 2016-03-11 at 5 08 46 pm](https://cloud.githubusercontent.com/assets/1155163/13716915/03462b2e-e7ac-11e5-91d5-1f028c41f547.png)

I bet if you staggered it by just a few hours you'll get access without competing for resources.

**Comment by lukecampbell** [comment]
We see this with a lot of the data servers, MARACOOS, GLOS and GliderDAC where everyone has their cron jobs set to midnight.
